### PR TITLE
New Logo/Icon and Minor layout changes in README.md

### PR DESCRIPTION
**Pull request by udz-codes**
#1 Created icon for the issue

### CODE REVIEW

**Comment by udz-codes** [comment]
If you would like any changes, let me know.

**Comment by yankeexe** [comment]
Hey @udz-codes this looks great, but I think we can tweak the color a little bit. How about we switch the colors of clock and globe and use `pastel colors` which are a bit dimmed.

**Comment by udz-codes** [comment]
> Hey @udz-codes this looks great, but I think we can tweak the color a little bit. How about we switch the colors of clock and globe and use `pastel colors` which are a bit dimmed.

Okay, and what do you think about it's background. Does that need any tweaking ?

**Comment by udz-codes** [comment]
### Hey @yankeexe , Here are 2 variants of the logo with changes you suggested. Tell me which one do you like, I will make pull request wirh that one.

#### 1. With thicker grid in background and pastel colors.


#### 2. Without background grid.

**Comment by yankeexe** [comment]
hey @udz-codes  I think I the non-grid looks great, you can send PR with that 🙂 

Thank you for your contribution. 🙏

**Review by yankeexe — APPROVED** [review]

**Pull request merged**
